# Generated by Django 4.1.4 on 2022-12-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_year', models.CharField(max_length=4)),
                ('movie_image', models.TextField(max_length=500)),
                ('movie_link', models.TextField(max_length=500)),
                ('movie_mainpage', models.BooleanField(default=False)),
            ],
        ),
    ]
