# Generated by Django 4.1.4 on 2022-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_detail',
            field=models.TextField(default='This category will be defined soon!', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_category',
            field=models.CharField(default='This category of this movie will be defined soon!', max_length=100),
        ),
    ]
